### ISSUE TITLE
Ability to add custom item with metadata & only pay to follow

### ISSUE THREAD

**Issue by the-w41k3r** [DarkSnakeX/VillagerFollow#2]
I was wondering if it is possible to allow only follow on pay and also ability to add items with custom metadata to follow so that it could be custom item even from another plugin.

**Comment by DarkSnakeX** [comment]
> if it is possible to allow only follow on pay
It is not possible at the moment, but I can implement it, give me some time and I will try to add it.

> ability to add items with custom metadata to follow so that it could be custom item even from another plugin
Can you give me an example of what type of custom item where you exactly thinking?

**Comment by the-w41k3r** [comment]
> Can you give me an example of what type of custom item where you exactly thinking?

in certain plugins for example CMI, there option to generate an emerald or in fact any item and give it a custom model data.
If it would be possible to check for custom model data of the item in hand rather than only checking for the emerald.

For example in config I set the follow item to be an iron ingot. Additionally, I am also able to set if the iron ingot has custom modeldata = followVillager then only an iron ingot with this model data will make the villagers follow or accept the item for pay to follow. You could also add a command `/villagerfollow giveitem`  to give the custom villager follow item.

**Comment by DarkSnakeX** [comment]
I will add it as possible thing to add in the future. I am not quite sure why you want this feature in the plugin, but if I have time I will research about it as I am not quite familiar with itemstack and metadata on spigot yet.

**Comment by the-w41k3r** [comment]
> I will add it as possible thing to add in the future. I am not quite sure why you want this feature in the plugin, but if I have time I will research about it as I am not quite familiar with itemstack and metadata on spigot yet.

No worries, it just seems to me that adding villager follow for just emeralds would make the game too easy and a custom item would allow servers to give custom items to players that may expire after a while or players would not be able to get them on their own. This would prevent players from stacking up villagers and farms easily and make the game more challenging.

**Comment by DarkSnakeX** [comment]
I get it, dont worry. Seems like a cool idea but as I said I will research about it first, thanks!

**Comment by DarkSnakeX** [comment]
Added in the last version the option to allow only follow on pay (1.5.7).
The other one will be added in the long run.
